// <auto-generated />
using System;
using BmaBackstage.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BmaBackstage.Infrastructure.Migrations
{
    [DbContext(typeof(BmaBackstageContext))]
    [Migration("20240529235305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttendanceRequirementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRequirementId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Progression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.ProgressionStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProgressionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgressionId");

                    b.ToTable("ProgressionStages");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProgressionStageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgressionStageId");

                    b.ToTable("Requirement");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Requirement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.StudentContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.TimeSheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("TimeSheetEntries");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Instructor", b =>
                {
                    b.HasBaseType("BmaBackstage.Infrastructure.DB.DataModel.People.Person");

                    b.Property<DateTime?>("LastBackgroundCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSafeSportTestDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Student", b =>
                {
                    b.HasBaseType("BmaBackstage.Infrastructure.DB.DataModel.People.Person");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.AgeRequirement", b =>
                {
                    b.HasBaseType("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.Requirement");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredAge")
                        .HasColumnType("INTEGER");

                    b.HasIndex("PersonId");

                    b.HasDiscriminator().HasValue("AgeRequirement");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.AttendanceRequirement", b =>
                {
                    b.HasBaseType("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.Requirement");

                    b.Property<int>("RequiredLessonCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("AttendanceRequirement");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.ManualApprovalRequirement", b =>
                {
                    b.HasBaseType("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.Requirement");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ManualApprovalRequirement");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.EmergencyContact", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Person", null)
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Lesson", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.AttendanceRequirement", null)
                        .WithMany("Lessons")
                        .HasForeignKey("AttendanceRequirementId");

                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Progression", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Instructor", null)
                        .WithMany("Progressions")
                        .HasForeignKey("InstructorId");

                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Student", null)
                        .WithMany("Progressions")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.ProgressionStage", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Progression", null)
                        .WithMany("Stages")
                        .HasForeignKey("ProgressionId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.Requirement", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.Progressions.ProgressionStage", null)
                        .WithMany("Requirements")
                        .HasForeignKey("ProgressionStageId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.StudentContract", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Student", null)
                        .WithMany("Contracts")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.TimeSheetEntry", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Instructor", null)
                        .WithMany("TimeSheet")
                        .HasForeignKey("InstructorId");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.AgeRequirement", b =>
                {
                    b.HasOne("BmaBackstage.Infrastructure.DB.DataModel.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Person", b =>
                {
                    b.Navigation("EmergencyContacts");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Progression", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.ProgressionStage", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Instructor", b =>
                {
                    b.Navigation("Progressions");

                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.People.Student", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Progressions");
                });

            modelBuilder.Entity("BmaBackstage.Infrastructure.DB.DataModel.Progressions.Requirements.AttendanceRequirement", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
